---
- name: test if umask is set correctly
  assert:
    that:
      - umask is defined
      - umask | int
    quiet: yes

- name: test if umask_users is set correctly
  assert:
    that:
      - umask_users is defined
      - umask_users | length > 0
      - umask_users is iterable
    quiet: yes
