---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check umask
      ansible.builtin.shell:
        cmd: ". /root/.bashrc && umask"
      changed_when: false
      register: umask_check_umask
      failed_when:
        - umask_check_umask.stdout != "0027"
