---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check umask
      ansible.builtin.shell:
        cmd: ". /root/.bashrc && umask"
      changed_when: no
      register: umask_check_umask
      failed_when:
        - umask_check_umask.stdout != "0027"
